// <auto-generated />
using System;
using JobRegistrationSubmisson.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobRegistrationSubmisson.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200915023548_Inittable")]
    partial class Inittable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobRegistrationSubmisson.Models.Accounts", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Tb_Account");
                });

            modelBuilder.Entity("JobRegistrationSubmisson.Models.AccRoles", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("Id");

                    b.Property<string>("RoleId");

                    b.Property<string>("RolesId");

                    b.HasKey("UserId");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_AccRoles");
                });

            modelBuilder.Entity("JobRegistrationSubmisson.Models.Employees", b =>
                {
                    b.Property<string>("EmpId");

                    b.Property<string>("Adress");

                    b.Property<DateTimeOffset>("CreateTime");

                    b.Property<DateTimeOffset>("DeleteTime");

                    b.Property<bool>("IsDelete");

                    b.Property<DateTimeOffset>("UpdateTime");

                    b.HasKey("EmpId");

                    b.ToTable("Tb_Employees");
                });

            modelBuilder.Entity("JobRegistrationSubmisson.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("JobRegistrationSubmisson.Models.AccRoles", b =>
                {
                    b.HasOne("JobRegistrationSubmisson.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.HasOne("JobRegistrationSubmisson.Models.Accounts", "Accounts")
                        .WithMany("AccRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobRegistrationSubmisson.Models.Employees", b =>
                {
                    b.HasOne("JobRegistrationSubmisson.Models.Accounts", "Accounts")
                        .WithOne("Employees")
                        .HasForeignKey("JobRegistrationSubmisson.Models.Employees", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
